openapi: 3.0.3
info:
  title: Daniel's Hello World App
  description: 'This is a Hello World App created by Daniel Wright for test purposes.'
  contact:
    email: danielalbertwright@gmail.com
  version: 1.0.0
tags:
  - name: All
    description: All APIs
servers:
  - url: 'http://localhost:8080/'
    description: Localhost
paths:
  /hello:
    get:
      tags:
        - All
      summary: Returns Hello World
      description: Returns Hello World in JSON
      operationId: helloworld
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hello'
components:
  schemas:
    Hello:
      type: object
      properties:
        message:
          type: string
          example: "Hello, world!"